[project]
name = "saas-crm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.18.4",
    "asyncpg>=0.31.0",
    "fastapi-mail>=1.6.2",
    "fastapi-users[oauth,sqlalchemy]>=15.0.5",
    "fastapi[standard]>=0.135.2",
    "loguru>=0.7.3",
    "psycopg[binary]>=3.3.3",
    "pydantic-settings>=2.13.1",
    "python-dotenv>=1.2.2",
    "python-jose[cryptography]>=3.5.0",
    "uvicorn>=0.42.0",
]
